name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          git clone https://github.com/mirumee/saleor-platform.git
          cd saleor-platform
          git clone https://github.com/mirumee/saleor-dashboard.git
          git clone https://github.com/mirumee/saleor-storefront.git
          git clone https://github.com/mirumee/saleor.git
          
      - name: docker buildddd
        run: docker-compose build
      
      - name: docker composeeee
        run: |
          docker-compose run --rm api python3 manage.py migrate
          docker-compose run --rm api python3 manage.py collectstatic --noinput
          docker-compose run --rm api python3 manage.py populatedb --createsuperuser
          
      - name: docker compse upppp
        run: docker-compose up      
